Standardization and systemd fix
osuosl-cookbooks/ucarp pull request #9
Opened 2016-12-20 22:14 UTC by knightsamar

Fixes the systemd problem described in #8 and also addresses the standardization task, partially.

Please note:

* rspec will fail because our fauxhai does not have support for 6.8 and upstream fauxhai does not support 7.3
* enabling ucarp service does not work on CentOS and Debian both.

2016-12-20 22:36 UTC, ramereth requested changes

2016-12-20 22:36 UTC, ramereth commented on .kitchen.yml
> +  - name: centos-7.3
The TK file needs to be updated per our spec.

2016-12-20 22:36 UTC, ramereth commented on metadata.rb
> +version          "1.0.3"
Why was this bump included in the PR?

2016-12-20 22:36 UTC, ramereth commented on metadata.rb
> +depends 'yum-epel','= 1.0.2'
You should have this be ``< 3.0`` instead.

2016-12-20 22:36 UTC, ramereth commented on recipes/default.rb
> +
Why was this added?

2016-12-20 23:28 UTC, knightsamar commented on .kitchen.yml
> +  - name: centos-7.3
I had actually fixed this in 53dace9532edd139.

And I can see the changes very well in my working directory too, which is completely in sync with this upstream branch.

2016-12-20 23:30 UTC, knightsamar commented on metadata.rb
> +version          "1.0.3"
I thought this was required to deploy the changes, since we are changing the `metadata.rb` to include `apt`. 

Do we not do that ?

2016-12-20 23:31 UTC, knightsamar commented on metadata.rb
> +depends 'yum-epel','= 1.0.2'
Done.

2016-12-20 23:32 UTC, knightsamar commented on recipes/default.rb
> +
I should have checked that earlier. Thanks for pointing out!

2016-12-20 23:34 UTC, fahlmant commented on metadata.rb
> +version          "1.0.3"
@knightsamar No, when we do a cookbook bump, this will automaitcally be changed. Its independednt of adding other changes to the metadata.

2016-12-20 23:50 UTC, ramereth commented on .kitchen.yml
> +  - name: centos-7.3
@knightsamar please consult with @fahlmant on what I mean when this needs to be fixed.

2016-12-20 23:51 UTC, ramereth commented
@knightsamar where are the tests for the data_bag recipe?

2016-12-21 00:09 UTC, knightsamar commented
@ramereth I am working on them. I was more worried about the ucarp resultin chef run failure so I thought I could push the specs in another PR while we get this changes deployed first.

2016-12-21 00:09 UTC, knightsamar commented on metadata.rb
> +version          "1.0.3"
Ok. noted @fahlmant

2016-12-23 01:46 UTC, knightsamar commented on .kitchen.yml
> +  - name: centos-7.3
@fahlmant I have updated the .kitchen.yml to look a bit more like other repos, in 021e7b08d5fab13
When you get time, please review and let me know.

2016-12-24 00:10 UTC, jldugger requested changes
Parse errors are leading to many unit test failures. Please fix that so I may continue the review.

2016-12-24 00:10 UTC, jldugger commented on recipes/default.rb
> +    if node['ucarp']['interface'] ~= /bond/
I'm having trouble finding any documentation of a `~=` operator. Based on other operators, I'd expect this to be an assignement operation, which, inside an `if` condition, would be a style bug.

It seems likely you meant to use `=~`, which is the pattern match operator. Is this correct?

2016-12-24 00:10 UTC, jldugger commented on spec/databag_spec.rb
> +=end
We have git commands to restore history; no reason to comment out code we don't intend to use.

2016-12-24 03:14 UTC, knightsamar commented on recipes/default.rb
> +    if node['ucarp']['interface'] ~= /bond/
Yes, =~ is the correct one.

2016-12-24 03:15 UTC, knightsamar commented on spec/databag_spec.rb
> +=end
Sorry, was testing things and pushed them before i was done.

2016-12-28 01:43 UTC, knightsamar commented
Testing and fixing rspecs on this is going to be very difficult unless I have proper fauxhai mockups since I cannot easily distinguish between what is an error caused by that versus a bug in my tests. So should I go ahead and create one and include it here for reference in someway?

2016-12-28 19:01 UTC, ramereth commented
@knightsamar I think given the future of us using this package are not looking good, I would just get the minimal tests we need and not worry about doing a comprehensive test suite for this. Considering this is a simple change, we just need to make sure the services for the platforms we care about do the basics.

2016-12-28 23:57 UTC, knightsamar commented
@ramereth ChefSpec tests don't work. ServerSpec tests work.

2016-12-29 17:19 UTC, ramereth commented
@knightsamar let's skip chefspec tests for now then.

2016-12-29 18:22 UTC, knightsamar commented
@ramereth ok. Should I submit a seperate PR with only the ServerSpecs so that they pass the CI and we can merge ?

2016-12-29 18:28 UTC, ramereth commented
@knightsamar you mean separate PR for the unit tests? I would keep the ServerSpec tests in this PR and remove the unit tests for now.

2016-12-29 18:31 UTC, knightsamar commented
Yep. Ok will do.

2016-12-30 19:47 UTC, knightsamar commented
@ramereth @fahlmant @jldugger All commits squashed into a single one with unit tests trimmed to work and serverspecs made reliable. Please give the final review.

2016-12-30 20:10 UTC, fahlmant requested changes
rubocop shows the following errors. running `rubocop --auto-correct` corrects all but one of these issues. 

```
attributes/default.rb:11:30: C: Unnecessary spacing detected.
default['ucarp']['init_type']  = value_for_platform(                                                                                                                     ^                                                                                                              attributes/default.rb:11:32: C: Operator = should be surrounded by a single space.                                                          default['ucarp']['init_type']  = value_for_platform(
                               ^
attributes/default.rb:19:25: C: Closing method call brace must be on the line after the last argument when opening brace is on a separate line from the first argument.
  'default' => 'upstart')
                        ^
recipes/data_bag.rb:38:3: W: Useless assignment to variable - paths.
  paths = %w(/etc/systemd/system /etc/systemd/system/multi-user.target.wants)
  ^^^^^
test/integration/default/serverspec/server_spec.rb:9:1: C: Missing space after #.
#TODO: Determine whether we should also check whether ucarp is started
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/integration/default/serverspec/server_spec.rb:10:1: C: Missing space after #.
#Is this recipe responsible for starting the ucarp service or not?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/databag_spec.rb:4:26: W: Unused block argument - p. You can omit the argument if you don't care about it.
  ALL_PLATFORMS.each do |p|
                         ^
spec/databag_spec.rb:15:13: C: Space missing to the left of {.
      expect{ chef_run }.to_not raise_error
            ^
spec/default_spec.rb:4:26: W: Unused block argument - p. You can omit the argument if you don't care about it.
  ALL_PLATFORMS.each do |p|
                         ^
spec/spec_helper.rb:40:51: C: Redundant curly braces around a hash parameter.
    stub_data_bag_item('ucarp', 'lb1').and_return({ ...
                                                  ^
spec/spec_helper.rb:41:7: C: Use 2 spaces for indentation in a hash, relative to the first position after the preceding left parenthesis.
      id: 'vip-lb1',
      ^^^^^^^^^^^^^
spec/spec_helper.rb:46:5: C: Indent the right brace the same as the first position after the preceding left parenthesis.
    })
    ^
```

foodcritic shows the following issues
```
FC064: Ensure issues_url is set in metadata: ./metadata.rb:1
FC065: Ensure source_url is set in metadata: ./metadata.rb:1
```

2016-12-30 20:48 UTC, knightsamar commented
Thanks @fahlmant. Fixed, squash, pushed.

2017-01-03 18:56 UTC, ramereth commented
@knightsamar please fix the rubocop issues otherwise it LGTM.

2017-01-05 01:00 UTC, jldugger requested changes

2017-01-05 01:00 UTC, jldugger commented on test/integration/default/serverspec/server_spec.rb
> +#Is this recipe responsible for starting the ucarp service or not?
need to separate with a space to pass rubocop.

2017-01-06 01:10 UTC, knightsamar commented
Fixed.

2017-01-06 01:26 UTC, ramereth approved these changes

2017-01-06 06:07 UTC, jldugger approved these changes

2017-01-06 16:37 UTC, fahlmant approved these changes

2017-01-06 21:07 UTC, ramereth commented
![](https://github.trello.services/images/mini-trello-icon.png) [ucarp: Remove manual systemd symlinks in databag recipe](https://trello.com/c/4BcMldgA/231-ucarp-remove-manual-systemd-symlinks-in-databag-recipe)

2017-01-06 22:56 UTC, knightsamar commented
Would this be considered a minor change or major to bump with ?

2017-01-06 23:14 UTC, ramereth commented
@knightsamar I would do a patch bump

2017-01-06 23:54 UTC, knightsamar commented
!bump patch *

2017-01-06 23:54 UTC, merged

2017-01-06 23:54 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.3.  Have a nice day!